replicaCount: 1
image:
  tag: nexus-docker-devsecops.apps.cluster-pn8ld.pn8ld.sandbox814.opentlc.com/ploigos/dotnet-app@sha256:82df1bb5380cf329adcb3c56c3f6a9c1f5a47869901ffa14319f01662de25cf9 # written by ploigos-step-runner
